### PR TITLE
Make prop types as externals since we have prop-types as dependencies

### PR DESCRIPTION
**Pull request by karelhala**
### Improves size of packs
Since we already have prop-types as dependencies no need to bundle them together to our packs. Let's export them using externals.

```diff
1,3c1,3
<                  Asset       Size               Chunks             Chunk Names
<        dynamic-form.js   43.4 KiB         dynamic-form  [emitted]  dynamic-form
<               forms.js    126 KiB                forms  [emitted]  forms
---
>                 Asset       Size               Chunks             Chunk Names
>        dynamic-form.js   9.96 KiB         dynamic-form  [emitted]  dynamic-form
>               forms.js   92.4 KiB                forms  [emitted]  forms
6,10c6,10
<          rbac-forms.js    193 KiB           rbac-forms  [emitted]  rbac-forms
<               table.js     53 KiB                table  [emitted]  table
<             tagging.js    1.2 MiB              tagging  [emitted]  tagging
<     textual_summary.js   80.6 KiB      textual_summary  [emitted]  textual_summary
<    vm-snapshot-form.js    183 KiB     vm-snapshot-form  [emitted]  vm-snapshot-form
---
>          rbac-forms.js    160 KiB           rbac-forms  [emitted]  rbac-forms
>               table.js   19.6 KiB                table  [emitted]  table
>             tagging.js   1.11 MiB              tagging  [emitted]  tagging
>     textual_summary.js   46.8 KiB      textual_summary  [emitted]  textual_summary
>    vm-snapshot-form.js    150 KiB     vm-snapshot-form  [emitted]  vm-snapshot-form
```

### CODE REVIEW

**Comment by karelhala** [comment]
@martinpovolny @PanSpagetka @Hyperkid123 assigned you all because it should effect all of our packs.

**Comment by himdel** [comment]
Makes sense :+1: :) Once https://github.com/ManageIQ/manageiq-ui-classic/pull/3776 is in, we may want to add `prop-types` to the list of shared dependencies.

**Comment by martinpovolny** [comment]
@himdel : is this good to be merged?

**Comment by himdel** [comment]
The js bits make sense, but I'm confused by `src/table/styles0.scss` .. @karelhala was that intentional?

**Comment by karelhala** [comment]
@himdel that's somthing which @Hyperkid123 brought, so I just "silently" removed it.

**Comment by martinpovolny** [comment]
Good to go then? @himdel ? @karelhala ?

**Comment by karelhala** [comment]
@martinpovolny still fine by me

**Pull request merged**
