### PR TITLE
Icon picker

### PR DESCRIPTION
**Pull request by fhlavac**
@Hyperkid123 @martinpovolny @terezanovotna 

- added array.prototype.flat to setupTests.js
- created font-icon, icon-list and icon-picker components
- created tests for font-icon, icon-list, icon-picker components and icon-picker-helper
- added icon-picker to storybook

### CODE REVIEW

**Comment by fhlavac** [comment]
@miq-bot add_reviewer @Hyperkid123

**Comment by terezanovotna** [comment]
Can we add more context? what is this supposed to do? where is it located? what is the goal of this picker? before and after and link to storybook?

**Comment by Hyperkid123** [comment]
@terezanovotna yep sorry about lack of info.

So this is a component where user can pick an icon and that is stored somewhere. For instance when user is creating custom button he can select an icon from this icon picker. It is also being used in toolbars.

Icons are divided into tabs based on the font and unfortunately they don't have fixed size. Every one is a bit different. That is why the second tab is more narrow than the first. 

What we don't know is the spacing/sizing of the icons, color of selected icon (that red rectangle). Because this is a re-write from angular to React it was never properly reviewed by UX.

I will also make sure that we have online storybook ASAP.

**Comment by Hyperkid123** [comment]
@terezanovotna storybook: http://miq-icon-picker.surge.sh/?selectedKind=Icon%20Picker&selectedStory=Icon%20Picker&full=0&addons=1&stories=1&panelRight=0&addonPanel=storybook%2Fstories%2Fstories-panel

You should see just one empty button.

If not go to Icon Picker > Icon Picker tab in menu

**Comment by martinpovolny** [comment]
The test failure seems relevant. Pls, fix it.

**Comment by martinpovolny** [comment]
Looks great.

@skateman : how much work is replacing the current (angular) implementation with this one?

**Comment by skateman** [comment]
@martinpovolny I don't think it's too much as we're able to call the foo_field_changed from reducers much easier than from angular. I'll take a look at it after I'm done with the remote console stuff.

**Comment by fhlavac** [comment]
@skateman 

- Improved icons alignment: same width at all tabs, added vertical spacing
- Changed color of selected icon
- Added highlighting of selected icon cell instead of highlighting the icon itself
- Fixed test failure

There is something wrong with storybook but sometimes works: http://icon-picker.surge.sh/?selectedKind=Icon%20Picker&selectedStory=Icon%20Picker&full=0&addons=1&stories=1&panelRight=0&addonPanel=storybook%2Fstories%2Fstories-panel

**Comment by skateman** [comment]
@fhlavac I like it, can you please add the `font-fabulous` icons to the demo as well? Just to make sure if it works...

**Comment by Hyperkid123** [comment]
@skateman we don't font-fabulous in react-ui-components

**Comment by Hyperkid123** [comment]
@fhlavac can you update the screenshots in description please?

**Comment by fhlavac** [comment]
@miq-bot remove_label wip

**Comment by skateman** [comment]
@Hyperkid123 ok, can you guarantee me that it will work in ui-classic?

**Comment by Hyperkid123** [comment]
We can link it and tests. But it will work as long as there is a stylesheet with `ff` prefix..

**Comment by skateman** [comment]
Well, isn't it easier just to add it here as a vendor/dev dependency? It doesn't have to be bundled with the final js/css.

**Comment by Hyperkid123** [comment]
@skateman Its not used anywhere. We will just link it and check it. Its no different from any other style sheet.

**Comment by Hyperkid123** [comment]
@epwinchell by anywhere I ment anywhere in react-ui-components. I am aware that is used all over the place in manageiq.

FF was never par of react-ui-components. 
Icon picker will have FF icons if you tell the component to use it. You can specify which fonts/icons it will use in component props. I just don't want to bake it into react-ui-components.

**Comment by skateman** [comment]
@Hyperkid123 if you want 1:1 symmetrical visual behavior with the icon picker in angular-ui-components, then IMO it should be visually as much accurate as possible. Also saying that it's not being used anywhere in the existing demo is not a reason to not promote our own stuff across projects. It would be used here ...

**Comment by Hyperkid123** [comment]
@skateman i have no idea what is the problem here. This icon picker supports font-fabulous and all the fonts that the angular does, its  just not in the demo. Am i missing something? We just don't want another dependency here just because of storybook that does not make any sense. Icon picker was not made specifically for font-fabulous or for any other font.

1:1 symmetrical visual behavior does not require any specific font. It should look exactly the same for every font. And if it does not then we have a visual issue which should be fixed. I really don't get what is the problem here.

**Comment by Hyperkid123** [comment]
@epwinchell i think i misunderstood. We will add it to the demo.

**Comment by Hyperkid123** [comment]
> @Hyperkid123 if you want 1:1 symmetrical visual behavior with the icon picker in angular-ui-component

@skateman how is this relevant for different font-types? I though the icon picker should look the same for every font. And if it does not then we have a problem.

> Also saying that it's not being used anywhere in the existing demo is not a reason to not promote our own stuff across projects. It would be used here ...

Thanks to PF react-ui-components has now somewhere around 21mb of static assests that are being exported with the library. I want to avoid any other dependencies as much as possible. I think you should understand that. But i do agree with the promotion so we sill add it as a dev dependency so it won be bundled into the library itself.

**Comment by Hyperkid123** [comment]
@skateman @epwinchell since this PR adds icon picker, once its merged we will create another PR which adds FF to the storybook later? I don't want to add stuff to @fhlavac which he was not supposed to do. What do you say about that?

**Comment by skateman** [comment]
@Hyperkid123 is it possible to not export the font-fabulous with the package?

**Comment by Hyperkid123** [comment]
@skateman yep as i said i will add it to dev dependencies and use it only in the storybook for this component. I just don't want add this tasks to @fhlavac.

**Comment by skateman** [comment]
I'm okay with that, thanks!

**Pull request merged**
